apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerstore-controller
  namespace: csi-powerstore
spec:
  template:
    spec:
      containers:
      - name: provisioner
          args:
            - "--volume-name-prefix=EKSA_CLUSTER_NAME-eksa-vol"
      - name: snapshotter
          args:
            - "--snapshot-name-prefix=EKSA_CLUSTER_NAME_eksa-snap"
