apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-snapshotter.yaml
  - ./csi-powerstore-namespace.yaml
  - ./csi-powerstore-secret.yaml
  - ./csi-powerstore-2.5.0.yaml
  - ./storageclass-powerstore-topology.yaml
  - ./volumesnapshotclass-powerstore.yaml
  - ./metallb.yaml
  - ./metallb-config.yaml
  - ./nginx-ingress-controller.yaml
  - ./ppdm-rbac.yaml
